-- CreateTable
CREATE TABLE `PAYMENT_ALLOCATION` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `payment_id` INTEGER NOT NULL,
    `room_type_id` INTEGER NOT NULL,
    `room_type_name` VARCHAR(100) NOT NULL,
    `amount` DECIMAL(12, 2) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `PAYMENT_ALLOCATION_payment_id_idx`(`payment_id`),
    INDEX `PAYMENT_ALLOCATION_room_type_id_idx`(`room_type_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PAYMENT_ALLOCATION` ADD CONSTRAINT `PAYMENT_ALLOCATION_payment_id_fkey` FOREIGN KEY (`payment_id`) REFERENCES `PAYMENT`(`payment_id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PAYMENT_ALLOCATION` ADD CONSTRAINT `PAYMENT_ALLOCATION_room_type_id_fkey` FOREIGN KEY (`room_type_id`) REFERENCES `ROOM_TYPE`(`room_type_id`) ON DELETE RESTRICT ON UPDATE CASCADE;
